services:
  - type: web
    name: expense-tracker-api
    env: python
    region: oregon
    plan: free
    
    buildCommand: >
      pip install --upgrade pip &&
      pip install --no-cache-dir -r backend/requirements.txt &&
      cd backend && alembic upgrade head

    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port 8000"

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: ENVIRONMENT
        value: production
