"""Fix reports table schema

Revision ID: 1c34981cddca
Revises: 
Create Date: 2026-05-07 22:54:43.744284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c34981cddca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_index(op.f('idx_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.alter_column('expense_categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('expense_categories', 'color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.alter_column('expense_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_categories_user_id'), table_name='expense_categories')
    op.drop_constraint(op.f('expense_categories_user_id_fkey'), 'expense_categories', type_='foreignkey')
    op.create_foreign_key(None, 'expense_categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('expense_categories', 'updated_at')
    op.drop_column('expense_categories', 'is_default')
    op.alter_column('expense_media', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_expense_media_expense_id'), table_name='expense_media')
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_expenses_category_id'), table_name='expenses')
    op.drop_index(op.f('idx_expenses_date'), table_name='expenses')
    op.drop_index(op.f('idx_expenses_user_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.drop_constraint(op.f('expenses_category_id_fkey'), 'expenses', type_='foreignkey')
    op.drop_constraint(op.f('expenses_user_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'expense_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('reports', sa.Column('period_start', sa.Date(), nullable=False))
    op.add_column('reports', sa.Column('period_end', sa.Date(), nullable=False))
    op.add_column('reports', sa.Column('total_expenses', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('total_borrowed', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('total_lent', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('generated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('idx_reports_user_id'), table_name='reports')
    op.drop_constraint(op.f('reports_user_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reports', 'period')
    op.drop_column('reports', 'file_url')
    op.drop_column('reports', 'file_size')
    op.drop_column('reports', 'created_at')
    op.alter_column('transaction_media', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_transaction_media_transaction_id'), table_name='transaction_media')
    op.alter_column('transactions', 'person_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transactions', 'given_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_transactions_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_status'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_user_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_expected_return_date'), 'transactions', ['expected_return_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'other_person_name')
    op.drop_column('transactions', 'description')
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('other_person_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_expected_return_date'), table_name='transactions')
    op.create_index(op.f('idx_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('idx_transactions_date'), 'transactions', ['date'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'given_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'person_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
    op.create_index(op.f('idx_transaction_media_transaction_id'), 'transaction_media', ['transaction_id'], unique=False)
    op.alter_column('transaction_media', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('reports', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('file_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('period', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_user_id_fkey'), 'reports', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_index(op.f('idx_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_column('reports', 'generated_at')
    op.drop_column('reports', 'total_lent')
    op.drop_column('reports', 'total_borrowed')
    op.drop_column('reports', 'total_expenses')
    op.drop_column('reports', 'period_end')
    op.drop_column('reports', 'period_start')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_user_id_fkey'), 'expenses', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(op.f('expenses_category_id_fkey'), 'expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.create_index(op.f('idx_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_index(op.f('idx_expenses_date'), 'expenses', ['date'], unique=False)
    op.create_index(op.f('idx_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.alter_column('expenses', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expenses', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.create_index(op.f('idx_expense_media_expense_id'), 'expense_media', ['expense_id'], unique=False)
    op.alter_column('expense_media', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('expense_categories', sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('expense_categories', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.create_foreign_key(op.f('expense_categories_user_id_fkey'), 'expense_categories', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_index(op.f('idx_categories_user_id'), 'expense_categories', ['user_id'], unique=False)
    op.alter_column('expense_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expense_categories', 'color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('expense_categories', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('audit_log_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('idx_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name=op.f('profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    # ### end Alembic commands ###
