"""
Word Report Generator
Generates Word documents
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import date
import io


class WordReportGenerator:
    """Generate Word reports."""

    @staticmethod
    def generate(report_data: dict, user_name: str) -> bytes:
        """Generate Word report from data."""
        doc = Document()

        # Title
        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title.add_run("💰 Expense Report")
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(31, 41, 55)

        # Header Info
        doc.add_paragraph()
        info_para = doc.add_paragraph()
        info_para.add_run("Report Generated: ").bold = True
        info_para.add_run(date.today().strftime("%B %d, %Y"))

        info_para = doc.add_paragraph()
        info_para.add_run("Period: ").bold = True
        info_para.add_run(
            f"{report_data['period_start'].strftime('%B %d, %Y')} - {report_data['period_end'].strftime('%B %d, %Y')}"
        )

        info_para = doc.add_paragraph()
        info_para.add_run("For: ").bold = True
        info_para.add_run(user_name)

        # Summary Section
        doc.add_paragraph()
        summary_heading = doc.add_heading("Summary", level=2)
        summary_heading.runs[0].font.color.rgb = RGBColor(55, 65, 81)

        table = doc.add_table(rows=4, cols=2)
        table.style = "Light Grid Accent 1"
        table.rows[0].cells[0].text = "Metric"
        table.rows[0].cells[1].text = "Amount"
        table.rows[1].cells[0].text = "Total Expenses"
        table.rows[1].cells[1].text = f"₹{report_data['total_expenses']:.2f}"
        table.rows[2].cells[0].text = "Total Borrowed"
        table.rows[2].cells[1].text = f"₹{report_data['total_borrowed']:.2f}"
        table.rows[3].cells[0].text = "Total Lent"
        table.rows[3].cells[1].text = f"₹{report_data['total_lent']:.2f}"

        # Category Breakdown
        doc.add_paragraph()
        category_heading = doc.add_heading("Category Breakdown", level=2)
        category_heading.runs[0].font.color.rgb = RGBColor(55, 65, 81)

        if report_data["category_breakdown"]:
            table = doc.add_table(rows=len(report_data["category_breakdown"]) + 1, cols=4)
            table.style = "Light Grid Accent 1"
            table.rows[0].cells[0].text = "Category"
            table.rows[0].cells[1].text = "Amount"
            table.rows[0].cells[2].text = "Percentage"
            table.rows[0].cells[3].text = "Count"

            for i, cat in enumerate(report_data["category_breakdown"], 1):
                table.rows[i].cells[0].text = f"{cat['icon']} {cat['name']}"
                table.rows[i].cells[1].text = f"₹{cat['amount']:.2f}"
                table.rows[i].cells[2].text = f"{cat['percentage']:.1f}%"
                table.rows[i].cells[3].text = str(cat['count'])

        # Payment Method Analysis
        doc.add_paragraph()
        payment_heading = doc.add_heading("Payment Method Analysis", level=2)
        payment_heading.runs[0].font.color.rgb = RGBColor(55, 65, 81)

        type_breakdown = report_data["type_breakdown"]
        table = doc.add_table(rows=3, cols=4)
        table.style = "Light Grid Accent 1"
        table.rows[0].cells[0].text = "Type"
        table.rows[0].cells[1].text = "Amount"
        table.rows[0].cells[2].text = "Percentage"
        table.rows[0].cells[3].text = "Transactions"
        table.rows[1].cells[0].text = "Cash"
        table.rows[1].cells[1].text = f"₹{type_breakdown['CASH']['amount']:.2f}"
        table.rows[1].cells[2].text = f"{type_breakdown['CASH']['percentage']:.1f}%"
        table.rows[1].cells[3].text = str(type_breakdown['CASH']['count'])
        table.rows[2].cells[0].text = "Digital"
        table.rows[2].cells[1].text = f"₹{type_breakdown['DIGITAL']['amount']:.2f}"
        table.rows[2].cells[2].text = f"{type_breakdown['DIGITAL']['percentage']:.1f}%"
        table.rows[2].cells[3].text = str(type_breakdown['DIGITAL']['count'])

        # Footer
        doc.add_paragraph()
        footer_para = doc.add_paragraph()
        footer_run = footer_para.add_run(
            f"This report was automatically generated by Smart Expense Manager on {date.today().strftime('%B %d, %Y')}."
        )
        footer_run.font.italic = True
        footer_run.font.size = Pt(10)

        # Save to bytes
        word_buffer = io.BytesIO()
        doc.save(word_buffer)
        word_buffer.seek(0)
        return word_buffer.getvalue()
